### PR TITLE
Reset list styling

### PR DESCRIPTION
**Pull request by benjy2429**
## Description

The masthead is currently setting `list-style: none` to all `<ol>` and `<ul>` elements on the page. This will reset the style to its default values.

See https://github.com/sky-uk/masthead/blob/26de12a4fc428cc3314f57cb6f260f3d13712b53/grunt/sass_includes/common/_reset.scss#L7

## Related Issue

n/a

## Motivation and Context

Any lists that are added to a page with the masthead present will not render with the correct styles, and instead will render bare. To fix this, this PR resets the styles to their default values. The masthead and footer are not affected by this change as they have more specific rules applied:
```
.skycom-footer .skycom-footer__nav>ul {
    list-style-type: none;
}
```

## How Has This Been Tested?

Manually tested in Sky Pages (see screenshots below)

## Screenshots (if appropriate)

**Lists with no classes added:**

screen shot 2016-11-18 at 11 46 51 am

**The footer is unaffected:**

screen shot 2016-11-18 at 11 46 56 am

## Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Browser Support
- [x] Chrome
- [x] Edge
- [x] Firefox
- [x] IE9
- [x] IE10
- [x] IE11
- [x] Opera
- [x] Safari
- [x] Mobile Devices
- [x] Screen-readers (e.g. JAWS, Apple VoiceOver)

## Checklist
- [x] All code includes full inline documentation (as per the [template](https://github.com/sky-uk/toolkit-core/blob/master/_template.scss)).
- [x] All code conforms to the Toolkit [coding style](https://github.com/sky-uk/toolkit/wiki/Coding-Style).
- [x] All code conforms to [WCAG 2.0 level AA Accessibility Guidelines](https://www.w3.org/TR/WCAG20/).
- [x] New functions and mixins have appropriate tests.
- [x] All new and existing tests passed.
- [x] I have added instructions on how to test my changes.
- [ ] Package version updated.
- [ ] CHANGELOG.md updated.

### CODE REVIEW

**Comment by joebell93** [comment]
Hmm not too sure this is something that belongs in the `_reset.scss`, more the defence layer in utilities:

https://github.com/sky-uk/toolkit-core/blob/master/utilities/_defence.scss

**Comment by benjy2429** [comment]
@joebell93 Yeah I wasn't too sure where to add this, I've moved it into the defence layer instead 👍

**Comment by joebell93** [comment]
Just curious - how does this look on prod vs. ran locally?

Wondering if webpack might be causing this bother as no-one's mentioned this before 🤔

**Comment by benjy2429** [comment]
It seems to be a problem on prod too, this is what's being applied:

```
#skycom-footer ol, #skycom-footer ul, #skycom-masthead-subnav ol #skycom-masthead-wrapper ol, #skycom-masthead-subnav ul, #skycom-masthead-wrapper ul, ol, ul {
    margin: 0;
    padding: 0;
    list-style: none;
```

from http://assets.sky.com/dist/1337/css/responsive-12.css.

Maybe this should be addressed in the masthead repo instead?

**Comment by joebell93** [comment]
@benjy2429 yeah that's what I'm thinking

**Comment by joebell93** [comment]
Closing due to the [Monorepo](https://github.com/sky-uk/toolkit) move

**Pull request closed without merging**
