### PR TITLE
Feature/container width global var

### PR DESCRIPTION
**Pull request by MrDinsdale**
## Description
Moved container max width (1140px + global-spacing * 2) to a separate `$global-container-max-width` variable to allow reuse.

## Related Issue
Requested in fluid-tile PR in toolkit-ui.

## Motivation and Context
Better reusability 

## Types of Changes
What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [x] New functions and mixins have appropriate tests.
- [x] All new and existing tests passed.
- [x] I have added instructions on how to test my changes.
- [ ] Package version updated.
- [x] CHANGELOG.md updated.

### CODE REVIEW

**Comment by joebell93** [comment]
Love it, but would it be tidier just to have `$global-container-width`?

**Comment by MrDinsdale** [comment]
I'm ok to change this to width however currently that is how the value is used across the Toolkit so `max-width` is a little more specific and potentially more readable. Either way is fine though.

**Comment by csswizardry** [comment]
Instead of defining a new global var, can we not just define the var in `objects/container`, sort of like so:

```scss
/* ==========================================================================
   OBJECTS / CONTAINER
   ========================================================================== */

...

$container-width: 1140px + ($global-spacing-unit * 2);
```

…and then in the files file:

```scss
$some-tile-var: $container-width !default;
```

Basically setting the tile constraint to whatever the container is, without having to move anything out globally.

**Comment by MrDinsdale** [comment]
Yep, like that. Will make the changes now.

**Pull request merged**
