### PR TITLE
Idea for handling breakpoint based hides

### PR DESCRIPTION
**Pull request by steveduffin**
## Description
Utility classes to hide content at various breakpoints

## Related Issue
https://github.com/sky-uk/toolkit-core/issues/149

## Motivation and Context
Useful for removing items visually that only make sense at certain screen sizes

## How Has This Been Tested?
http://codepen.io/mavrick91/pen/xgbJqG

## Types of Changes
What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Browser Support
- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE9
- [ ] IE10
- [ ] IE11
- [ ] Opera
- [ ] Safari
- [ ] Mobile Devices
- [ ] Screen-readers (e.g. JAWS, Apple VoiceOver)

## Checklist
- [ ] All code includes full inline documentation (as per the [template](https://github.com/sky-uk/toolkit-core/blob/master/_template.scss)).
- [ ] All code conforms to the Toolkit [coding style](https://github.com/sky-uk/toolkit/wiki/Coding-Style).
- [ ] All code conforms to [WCAG 2.0 level AA Accessibility Guidelines](https://www.w3.org/TR/WCAG20/).
- [ ] New functions and mixins have appropriate tests.
- [ ] All new and existing tests passed.
- [ ] I have added instructions on how to test my changes.
- [ ] Package version updated.
- [ ] CHANGELOG.md updated.

### CODE REVIEW

**Comment by joebell93** [comment]
Could we not calculate this using some sort of loop?

**Comment by joebell93** [comment]
Gonna do some more investigation into this. As useful as I think these things are, it could lead to a very bloated stylesheet

**Comment by steveduffin** [comment]
You are quite right. I wanted to make sure the outcome was the correct approach before I had a stab at refactoring into a loop which would take me a little more time to figure out

**Comment by joebell93** [comment]
This went live a separate PR by @skitson  🚀

**Pull request closed without merging**
